export const Data = [
    {
        _id: 1,
        ques: 'Evolutionary convergence is characterised by',
        a: 'development of characteristics by random mutations.',
        b: 'development of similar characteristics in different groups of organisms of different ancestry.',
        c: 'development of dissimilar characteristics in closely related groups of organisms.',
        d: 'development of similar characteristics in related groups of organisms.',
        ans: 'b',
    },
    {
        _id: 2,
        ques: 'Homologous organs indicate',
        a: 'convergent evolution.',
        b: 'divergent evolution.',
        c: 'adaptive radiation.',
        d: 'natural selection.',
        ans: 'b',
    },
    {
        _id: 3,
        ques: 'Dability to defend itself.',
        a: 'ability to defend itself.',
        b: 'strategy to obtain food.',
        c: 'number of offspring produced.',
        d: 'dominance over other individuals.',
        ans: 'c',
    },
    {
        _id: 4,
        ques: 'Change of frequency of alleles in a population results in evolution. This statement is proposed in',
        a: 'Darwin’s theory',
        b: 'Lamarck’s theory',
        c: 'Hardy-Weinberg principle',
        d: 'de Vries theory.',
        ans: 'c',
    },
    {
        _id: 5,
        ques: 'Select the correct statement from the following options.',
        a: 'Mutations are random and directional.',
        b: 'Darwinian variations are small and direction less.',
        c: 'Fitness is the end result of the ability to adapt and get selected by nature.',
        d: 'All mammals have evolved vivipary as an adaptation.',
        ans: 'c',
    },
]
